cursor #8d5a26
cursor_text_color background

foreground            #efe0d5
background            #19120c
selection_foreground  #412c19
selection_background  #e2c0a4
url_color             #feb877

# black
color8   #262626
color0   #4c4c4c

# red
color1 #cc0403
color9 #f2201f

# green
color2  #19cb00
color10 #23fd00

# yellow
color3  #cecb00
color11 #fffd00

# blue
color4  #feb877
color12 #1a8fff


# magenta
color5  #cb1ed1
color13 #fd28ff


# cyan
color6  #0dcdcd
color14 #14ffff


# white
color7  #dddddd
color15 #ffffff

