wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/soul-cinder.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/Pictures/wallpapers/soul-cinder.png
    fit_mode = cover
}

