background {
  monitior =
  path = $HOME/Pictures/wallpapers/AW2_Dusk-scaled.jpg
}

label {
  monitor =
  text = Hi, $USER
  font_family = JetBrains Mono Bold 
  font_size = 48
  position = 0, 100
}

input-field {
  monitor =
  size = 600, 60
  font_family = JetBrains Mono Bold
  inner_color = rgba(125,125,125,0.2)
  placeholder_text = password 
}
