cursor {{colors.source_color.default.hex}}
cursor_text_color background

foreground            {{colors.on_background.default.hex}}
background            {{colors.background.default.hex}}
selection_foreground  {{colors.on_secondary.default.hex}}
selection_background  {{colors.secondary.default.hex}}
url_color             {{colors.primary.default.hex}}

# black
color8   #262626
color0   #4c4c4c

# red
color1 #cc0403
color9 #f2201f

# green
color2  #19cb00
color10 #23fd00

# yellow
color3  #cecb00
color11 #fffd00

# blue
color4  {{colors.primary.default.hex}}
color12 #1a8fff


# magenta
color5  #cb1ed1
color13 #fd28ff


# cyan
color6  #0dcdcd
color14 #14ffff


# white
color7  #dddddd
color15 #ffffff

